# Generated by Django 4.2.6 on 2023-11-28 11:38

from django.db import migrations

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id_alter_postmedia_post'),
    ]

    operations = [
    ]
