# Generated by Django 4.2.6 on 2023-11-28 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20231128_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='uuid',
        ),
    ]
