# Generated by Django 4.2.6 on 2023-11-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_rename_id_post_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uuid',
            new_name='id',
        ),
    ]
