# Generated by Django 4.2.6 on 2023-11-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_hasthtag_post_hashtags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HasthTag',
            new_name='HashTag',
        ),
    ]
